trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'prasadashila'
    repository: '$(prasadashila)/$(exampleApp)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/charts'
    ArtifactName: 'charts'
    publishLocation: 'Container'
